### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Burkes** [karahanbuhan/wootboost#1]
Votes don't affect gains on plug.dj

**Comment by karahanbuhan** [comment]
As I know there is a daily limit for the woots making you gain. After the limit it just doesn't affect. If voting works but points then it is nothing to do with the script. I'd be happy if you could share more information.

**Comment by sperrichon** [comment]
I'd like to point out that Burkes is a plug.dj Brand Ambassador

**Comment by karahanbuhan** [comment]
I see what you mean. I am an old user of plug.dj so didn't notice the update, description changed.

**Comment by Burkes** [comment]
Each `earn` event can award the user PP (Plug Points) and XP (Experience Points), they are emitted every 5 minutes that you are online. The limit is 72 ticks (`earn` events) and it resets at midnight GMT. Once you start your fresh daily session of plug.dj, you start earning PP and XP at random values that decrease over each tick.

Multiple users have experimented leaving their accounts online and monitoring the experience gains with variations of: purely online, voting each song, DJing while others vote their songs, chatting, and others. None have proved to increase the XP gain.
